name: Build Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch
    paths:
      - '**/Dockerfile'  # Trigger on changes to any Dockerfile in any folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (optional for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Loop through all directories containing a Dockerfile
      - name: Build Docker image for modified folders
        run: |
          # Loop through all modified directories containing Dockerfiles
          modified_dirs=$(git diff --name-only $GITHUB_SHA^..$GITHUB_SHA | grep '/Dockerfile' | cut -d'/' -f1-2 | sort -u)
          
          for dir in $modified_dirs; do
            echo "Building Docker image for $dir"
            docker build -t test-image-${dir} ./$dir
          done
