name: Docker Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Dockerfiles
        run: |
          for dir in $(find . -name 'Dockerfile' -exec dirname {} \;); do
            echo "Building Dockerfile in $dir"
            docker build "$dir"
          done
