name: Docker Image CI

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch
    paths:
      - '**/Dockerfile'  # Trigger on changes to any Dockerfile in any folder

jobs:
  build:
    runs-on: ubuntu-20.04  # Use a specific Ubuntu version

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker (use GitHub Token for DockerHub or GHCR)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

      # Step 3: Loop through all directories containing Dockerfiles and build them
      - name: Build Docker images for modified Dockerfiles
        run: |
          # Find modified Dockerfiles and build images for the corresponding directories
          modified_dirs=$(git diff --name-only $GITHUB_SHA^..$GITHUB_SHA | grep '/Dockerfile' | cut -d'/' -f1-2 | sort -u)
          
          for dir in $modified_dirs; do
            echo "Building Docker image for $dir"
            docker build -t my-image-name-${dir//\//-}:$(date +%s) ./$dir
          done
