name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Docker Buildx (optional for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Build Docker images for all modified Dockerfiles in the repo
    - name: Build Docker images for all Dockerfiles
      run: |
        # Loop through all directories containing Dockerfiles and build them
        find . -name 'Dockerfile' | while read dockerfile; do
          dir=$(dirname "$dockerfile")  # Get the directory containing the Dockerfile
          echo "Building Docker image for directory $dir"
          docker build -t my-image-name-${dir//\//-}:$(date +%s) -f "$dockerfile" "$dir"
        done
